CC	= gcc
OPT	= -g -O3
CHIP	=
ISA	=
DEFS	= -DDATA_ANALYSIS
LIBS	= -lm
CFLAGS  = $(OPT) $(CHIP) $(ISA) $(DEFS) $(XOPT)
BLASFLAGS = -L/usr/lib64/atlas -lsatlas
SOURCES = datatools.c main.c matmul.c
OBJECTS = $(SOURCES:.c=.o)

all: main

main: $(OBJECTS)
	$(CC) $(CFLAGS) -o $@ $(OBJECTS) $(LIBS)

clean:
	rm -f main $(OBJECTS)
